### ISSUE TITLE
Use `local` backend instead of `-state` CLI option for local state

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1430]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We [currently specify the `-state` option](https://github.com/hashicorp/terraform-cdk/blob/6f7dbdd90403867a5a6e42d501c403371c03a370/packages/cdktf-cli/bin/cmds/ui/models/terraform-cli.ts#L121) for setting the Terraform state file location for local state. We even seem to set this when another backend is set (but it has no effect then).
The `-state` option is deprecated and we should stop using it. We should use the explicit [`local` backend](https://www.terraform.io/language/settings/backends/local) instead.

### References

* https://github.com/hashicorp/terraform/issues/30195

**Comment by apparentlymart** [comment]
Some extra context here:

In Terraform v0.8 and earlier, Terraform CLI had a very different model for state management where by default it would store state locally but users could explicitly opt in to using a remote storage location by running `terraform remote config ...` followed by numerous other options. This interface was not particularly ergonomic and required each user of that Terraform configuration to get the configuration _just right_ or else pretty horrible things could happen, such as accidentally overwriting the remote production state with a local state.

That less-ergonomic interface was a result of remote state storage having been retrofitted into Terraform CLI later. Prior to that feature existing, it was possible to "fake it" by running Terraform in automation that would handle state fetching and storing itself, and that sort of automation is what might typically use the `-state` argument if, for example, it wanted to read and update the state in a temporary directory rather than directly in the working directory. In those very early days of Terraform there wasn't any strong sense of things being "deprecated" because the product was still very early and the team was constantly learning from each change, but from a practical standpoint much of the need for the `-state` argument was replaced by `terraform remote config` when it was introduced, though some uses remained.

Terraform v0.9 introduced the idea of _state backends_ which made the problem of state storage first-class and configured inside the Terraform configuration itself. That meant that the settings would live inside version control and `terraform init` could initialize state storage without any arguments, and so there was much less risk of someone entering an incorrect remote configuration. As a measure of continued backward compatibility, we included the following mechanisms:
* The `-backend-config` option to `terraform init` retains the capability from `terraform remote config` of setting some of the settings on the command line rather than in the configuration. Although we don't typically recommend that, it remains useful in some automation scenarios. (Terraform Cloud in particular eschews this in favor of generating its own `backend` block just before running Terraform.)
* The `-state` argument (and the other similar legacy options) became settings only for the special `local` backend, which is active by default if no other backend configuration is present. This therefore preserves compatibility with the _really old_ automation flows that don't use Terraform CLI's remote state storage at all, and instead do their own work with state snapshots in a temporary directory.

When using the local backend, `-backend-config` can actually hit all of the same use-cases as the legacy `-state` argument can, and so in a sense it's now _double-deprecated_ because it's been made redundant twice over by other features.

---

With all of that said, looking at the code you linked as "we currently specify the `-state` option" it _looks_ like you're using that effectively as a cdktf-specific reimplementation of [Workspaces](https://www.terraform.io/language/state/workspaces). When using the local backend, each workspace has a separate `.tfstate` file _just like_ what that codepath seems to be aiming to achieve, albeit in a subdirectory `terraform.d` rather than directly in the working directory. When using other backends which support workspaces, the storage details are different but the overall mechanism is the same: each workspace has its own separate latest state snapshot.

Getting from this custom approach to using the built-in workspaces mechanism may not be easy due to backward-compatibility of cdktf _itself_, but if you are interested in evaluating that path then I'd suggest looking at [the environment variable `TF_WORKSPACE`](https://www.terraform.io/cli/config/environment-variables#tf_workspace) as a straightforward way to force a particular workspace for a particular operation like seems to be the goal of using the `-state` option here. That environment variable takes priority over the working directory's mutable workspace selection (with `terraform workspace select`) and so is a good choice for automation like this which has its own sense of which workspace it's intending to work on with a particular command.

**Comment by jsteinich** [comment]
> With all of that said, looking at the code you linked as "we currently specify the `-state` option" it _looks_ like you're using that effectively as a cdktf-specific reimplementation of [Workspaces](https://www.terraform.io/language/state/workspaces).

I managed to track back to the [original commit](https://github.com/hashicorp/terraform-cdk/commit/4cd16d45c6792ff5726fd2b02a875e8d248072b2) for using the state argument. Looks like the intention was just to change the location of the file.
Also, while the code is parameterizing the state file name, it's actually already segmented into different directories at a higher level, so we shouldn't need to worry about converting to workspaces.

Adding in a local backend that maps to the existing file shouldn't be too hard for new projects, but definitely something to keep in mind for existing projects. Could probably completely automate if desired. Or maybe an upgrade command like Terraform uses.

**Comment by iainlbc** [comment]
Here is some added context on how this impacts us as an end user evaluating cdktf:

As a first step of our cdktf journey we need to bootstrap the remote state DynamoDB & S3 resources. Historically all of our IaC includes integration tests that spin up resources, validate their attributes, then tear them down. So this impacts our current approach to integration testing and our ability to robustly bootstrap our env's state storage. Does anyone have any ideas for workarounds?
