### ISSUE TITLE
Docs: Recommendations for configuring Terraform Cloud

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1554]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

Docs on how to connect CDK for Terraform with Terraform Cloud should be easier to find. We should have dedicated docs that go into detail about how to work with Terraform Cloud. 
See[ Asana ticket ](https://app.asana.com/0/1202131070585428/1202186558531943)for more detail. 

### Actual Behavior

Our current recommendations are [kinda hidden in the setup guide](https://www.terraform.io/cdktf/create-and-deploy/project-setup#use-terraform-cloud-as-a-remote-backend).

### References

- https://github.com/hashicorp/terraform-cdk/issues/670#issuecomment-1031016915

**Comment by laurapacilio** [comment]
@DanielMSchmidt and I discussed, and he will start drafting this page content. Here are the notes from our meeting/the initial direction we are taking. Feedback is always welcome :-) 

**GOALS FOR PAGE**
- Something to link to - We want to collect information/links to information about how work with TFC in one place. This should be helpful for users who are in our documentation set and are searching for "Terraform Cloud" in the sidebar. It will also help when answering questions to link folks to one cohesive page.
- Explain TFC & Key Concepts - We are assuming that some users who have started using CDKTF and are considering Terraform Cloud may not be very familiar with Terraform or infrastructure concepts. As such, we want to do a bit more on this page to explain some high-level components of how TFC works (e.g., remote vs. local execution and why someone would choose each one) and then provide more targeted links to parts of the TFC documentation where users can learn more. We want to provide a more guided tour, rather than simply linking to the TFC doc set and asking folks to figure out what things are and why they are useful/relevant. 

——
**OUTLINE**
- Introduction
   - 1-3 sentences introducing TFC/TFE and explaining what's on this page.
   
- Why Terraform Cloud & Terraform Enterprise?
    - Brief description of what TFC and TFE are; link to intro pages.
    - You may want to use Terraform Cloud when you need: 
       - Certain features like policy enforcement or the private registry
       - Organization uses TFC already and you want to use it as well
       - You want to use TFC for credential/secrets management
       
- Connect to /Set Up to Terraform Cloud
    - Connecting your app (break up explanation; do some code examples) - pull out of Project Setup Page
    - Include instructions or explanation of how this works for TFE as well
    
- Deploying your Application with Terraform Cloud
   - Explain a bit about local vs. remote execution and what one you should choose (link to appropriate TFC pages)
   - How to set up a VCS connection for TFC and why this is useful for CDKTF (useful for CI; link to existing page)

- Variables
    - How can you set them up (brief explanation + link to the variables docs in TFC)
    - When can your CDKTF app access them?
    - Any tips to make sure things work properly? Execution mode matters, right?
    - Variables and Variable Sets for Secrets Management (briefly explain what this means and why you'd want it + link to best practices page)

- Continuous Integration 
    - Brief explanation about how you can do this + link to CI page

- Policy Enforcement 
    - Explain that you can use Sentinel policies; link to docs
    - Explain that you can use Run Tasks; link to docs
— 

**CONSOLIDATE**
CI Page & Best Practices - Don't repeat content; provide brief explanation and link to the page where things live
