### ISSUE TITLE
Support Terraform Cloud configuration

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#1583]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm not sure what the difference is, but the Terraform documentation recommends using the Terraform Cloud Configuration rather than the remote backed.

### References

- https://www.terraform.io/language/settings/backends/remote
- https://www.terraform.io/language/settings/terraform-cloud

**Comment by nikolay** [comment]
I submitted a dupe before I searched and found this so that I will close in favor of this issue, but, surprisingly, HashiCorp has not implemented this, which better supports their commercial customers! So I am beginning to think that they don't use their own commercial products if the support has been unavailable since day 1!
