### ISSUE TITLE
Support Java

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#197]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow writing Terraform CDK code in Java

- Update jsii config to add in Java
- Add example Java project
- Add Java project template
- Add tests

### References

Similar to [Python Work](https://github.com/hashicorp/terraform-cdk/pull/51)

**Comment by fred-opplane** [comment]
Java is a much better backend language then Javascript.

**Comment by musha68k** [comment]
+100 This would in theory also unlock all the other much more mature languages in the JVM ecosystem - Scala, Clojure, etc ...

**Comment by raj-saxena** [comment]
I would love to contribute support for Kotlin if I can get some guidance on how to approach this. 

I can try to guess my way around from the referenced PR but that might not be the most productive way forward. @anubhavmishra does the team already have some docs on how to get started?

**Comment by skorfmann** [comment]
> I would love to contribute support for Kotlin if I can get some guidance on how to approach this.

Since we're using [jsii](https://github.com/aws/jsii) this [issue](https://github.com/aws/jsii/issues/1541) would be a good starting point. 

> I can try to guess my way around from the referenced PR but that might not be the most productive way forward.

When starting to work on Java, we'll switch to [jsii-srcmak](https://github.com/aws/jsii-srcmak) for the CLI code generator / harvester. Other than that, it's mostly setting up the `cdktf` package [jsii config](https://github.com/hashicorp/terraform-cdk/blob/5becfbc699180adfe920dec794200bbf56dda0a7/packages/cdktf/package.json#L14-L23), checking for compilation errors, adding integration tests and setting up the publishing pipeline.

Except for the publishing pipeline, I think all the other stuff would be perfect for contributions. I'd be more than happy to help if someone is up for that.
