### ISSUE TITLE
Provide the version of the providers in the release notes?

### ISSUE THREAD

**Issue by karfau** [hashicorp/terraform-cdk#1976]
We are currently using `cdktf get` to get providers.
I would like to switch to the installing them as npm dependencies.
And I would prefer to install the exact version that we are using now.
But this information is really hard to track.
Would it be possible to provide minimal "release notes" that just give an overview of the provider versions they include?

Another possibility might be to add the version number to the commit when doing a provider upgrade, this way the history of the package.json would provide the information I'm looking for.

The easiest way I found to find the information I was looking for it to check the version of package.json for tag, e.g. the version I was looking for is is present from 
https://github.com/hashicorp/cdktf-provider-aws/blob/v7.0.63/package.json
to
https://github.com/hashicorp/cdktf-provider-aws/blob/v8.0.2/package.json

(Also in the major versions it would be nice to know what is the breaking change.)

**Comment by mutahhir** [comment]
Due to how [standard-version](https://www.npmjs.com/package/standard-version) works, it'll be really hard to include the version number of the provider on each release. However, a more doable alternative has been to improve the commit messages on provider version changes and the PR title. Unfortunately, I don't have an example at the time of writing this, but I'll update it with examples of how it looks when a new release is generated with the new PR titles

**Comment by mutahhir** [comment]
Example release: https://github.com/cdktf/cdktf-provider-google/releases/tag/v3.0.16.

Going to mark it as closed for now, but happy to hear how we can improve this more.

**Comment by karfau** [comment]
This is really awesome, thx
