### ISSUE TITLE
Unable to maintain a persistent EBS Volume

### ISSUE THREAD

**Issue by ryangniadek** [hashicorp/terraform-cdk#1977]
Hi all - for my project, I need to maintain a persistent EBS volume that I attach to when using `cdktf deploy` and detach from, but not actually destroy when running `cdktf destroy`. I am unable to figure out how to do this using the provided documentation, was hoping there was either a supported way to accomplish this or if not, if this is something that could be added. Originally, I tried the `skipDestroy` attribute on VolumeAttachment but I do want to destroy the attachment, I just don't want to destroy the actual volume itself.

Excerpt of my current set up
```typescript
    const postgres = new ec2.Instance(this, "postgres-sandbox", {
      ami: "ami-0ee8244746ec5d6d4",
      instanceType: "t2.micro",
      keyName: //redacted,
      subnetId: //redacted,
      associatePublicIpAddress: false
    });

    const ebsVolume = new ec2.EbsVolume(this, "defaultEbs", {
      size: 300,
      type: "gp2",
      availabilityZone: postgres.availabilityZone,
      dependsOn: [postgres],
      tags: {
        name: postgres.id
      }
    })

    const attach = new ec2.VolumeAttachment(this, "VolumeAttachment", {
      deviceName: "/dev/sdf",
      volumeId: ebsVolume.id,
      instanceId: postgres.id,
      stopInstanceBeforeDetaching: true,
      dependsOn: [postgres, ebsVolume]
    })
```

**Comment by jsteinich** [comment]
I believe you'll want to use [a lifecycle rule](https://www.terraform.io/language/meta-arguments/lifecycle#prevent_destroy) on the volume to prevent destruction.
You'll likely also want to pull the volume into a different stack since its lifespan doesn't match with the other resources being created.

**Comment by ansgarm** [comment]
Hi there 👋

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47) where there are more people ready to help.

Thanks!
