### ISSUE TITLE
Not able to create API Proxies for gcp

### ISSUE THREAD

**Issue by bmakumar** [hashicorp/terraform-cdk#1993]
Hi Team,

Trying to create apigee using cdktf but the document provided helps in creating only endpoints , environments, organizations and instance.  cannot we create a API Proxy or is it still under development.

If i am missing the steps from the documentation  on how to create the api proxy , please do let me know.

Also if possible can you share the sample snippet on how to create the api proxy from apigee if available that would be helpful.

Apigee CDKTF Doc Link i am referring to:  https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_instance_attachment

Thanks

**Comment by ansgarm** [comment]
Hi there 👋

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47) where there are more people ready to help.

Thanks!
