### ISSUE TITLE
Are object namings for S3 bucket versioning correct?

### ISSUE THREAD

**Issue by knakayama** [hashicorp/terraform-cdk#2017]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

```
- cdk-provider-aws: v9.0.12
```

### Description

In [cdktf-provider-aws](https://github.com/hashicorp/cdktf-provider-aws), there are objects [like here](https://github.com/hashicorp/cdktf-provider-aws/blob/v9.0.12/src/s3/s3-bucket-versioning.ts) for configuring S3 bucket versioning. But some of them are prefixed as`S3BuketVersioningA`, not `S3BucketVersioning`, let's say [a class](https://github.com/hashicorp/cdktf-provider-aws/blob/v9.0.12/src/s3/s3-bucket-versioning.ts#L129). The names are intentionally made? I believe there would be better namings even in case where the names are conflict with existing objects. If you have a plan to change the names, I would appreciate it as a CDKTF user,.

Thank you for making great tools btw!

**Comment by ansgarm** [comment]
Hi @knakayama 👋

Yes, those are intentionally named that way. In this case the `s3-bucket.ts` already [exports an interface named `S3BucketVersioning`](https://github.com/hashicorp/cdktf-provider-aws/blob/dc1101297913cd7f88c87e78f903bea14ee85799/src/s3/s3-bucket.ts#L3111) which would collide with the other name. And we need to have unique names within each pre-built provider because JSII requires us to export all classes that need bindings for other languages.
And as this is automatically generated based solely on the Terraform provider schema and not written by hand, we can't name this resource differently.

Slightly related older issue: #1804 (linking it for discoverability of this issue in the future)

**Comment by knakayama** [comment]
@ansgarm Thank you for a quick response. Now I understand the naming reason. I wish there could be a better solution to deal with this.

Anyway, thank you so much! I will close this issue.

**Comment by jsteinich** [comment]
> I wish there could be a better solution to deal with this.

It should be possible to make the name collision handling smarter and always keep the desired name for the main resource class (they are unique within a provider). We'd still run into an issue with the additional generated type(s), but that should be easier to handle if working in an IDE.
