### ISSUE TITLE
`aws` provider: module cdktf has no ISSHProvisionerConnection

### ISSUE THREAD

**Issue by ignaloidas** [hashicorp/terraform-cdk#2074]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.12.2
Python 3.9.12
cdktf-cdktf-provider-aws 9.0.15

### Affected Provider / Resource(s)

The entire provider

### Debug Output

https://gist.github.com/ignaloidas/e441474bfc37f021b08f6bc614807102

### Expected Behavior

Provider works

### Actual Behavior

Provider fails on import

### Steps to Reproduce

from cdktf_cdktf_provider_aws import AwsProvider 

### Important Factoids

Nothing

**Comment by ignaloidas** [comment]
Seems like this is caused by a failed check on an upgrade https://github.com/hashicorp/cdktf-provider-aws/pull/714

**Comment by ansgarm** [comment]
Hi @ignaloidas,

thank you for reporting this!
Damn, it seems that [this change](https://github.com/hashicorp/terraform-cdk/pull/2042) (which was supposed to be an `cdktf` lib internal change only) does in fact affect the generated code in at least Python and possibly other languages. We did not notice this because the generated TypeScript code has no direct references to the changed interface (only an cdktf internal super class is referencing it). But it seems that in some languages (e.g. Python) the generated provider bindings contain mentions of that (now renamed) interface.

Until we release a new version for the pre-built provider you'd need to stay on version 0.12.1, I'm afraid. Or use locally generated provider bindings instead.

**Comment by ansgarm** [comment]
Hi @ignaloidas 👋

Could you try [v9.0.16](https://github.com/hashicorp/cdktf-provider-aws/releases/tag/v9.0.16) that was just released together with `cdktf` v0.12.2?

**Comment by ignaloidas** [comment]
Hi @ansgarm 
It has indeed fixed the problem, but I found out that kubernetes provider has the same problem. Might be worth checking over all prebuilt providers whether they have this problem.

**Comment by ignaloidas** [comment]
Quickly going through provider repositories, I think the providers still affected by this are:

- [ ]  `yandex`
- [ ]  `kubernetes`
- [ ]  `azurerm`
- [ ]  `google`
- [ ]  `googlebeta`

**Comment by ansgarm** [comment]
Hi @ignaloidas 👋

Oh, yeah. I ran the fix for all the repositories but that seemed to have failed in some, due to different other errors. For example for kubernetes it had an out of memory error when building Go in the [update PR](https://github.com/hashicorp/cdktf-provider-kubernetes/pull/1171), which caused that PR to not be merged automatically.

I will look into this and keep you posted here.

**Comment by ansgarm** [comment]
Hi @ignaloidas, I just rolled out a fix that allows those resource-heavy pre-built providers to build and release again.

`cdktf-cdktf-provider-kubernetes 2.0.10` is [available on PyPI](https://pypi.org/project/cdktf-cdktf-provider-kubernetes/2.0.10/) now 👍

**Comment by ignaloidas** [comment]
Hey, seems like the providers we use have indeed all been fixed, though there still seems to be errors with `yandex` and `datadog` providers. I think it's worth keeping this issue open till those ones have been fixed, even though ones I care about have been. Thanks for your efforts!

**Comment by ansgarm** [comment]
Thanks for the hint with DataDog! Fixed that one as well 👍
Regarding Yandex: That one has been [recently removed](https://github.com/hashicorp/cdktf-repository-manager/pull/106) and the repo won't receive future updates and will be archived soon.

**Comment by ignaloidas** [comment]
Great! Thanks for fixing this!
