### ISSUE TITLE
Allow skipping stacks with no changes

### ISSUE THREAD

**Issue by jld-adriano** [hashicorp/terraform-cdk#2116]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We use multi stack deployments quite frequently during development, using "*", but do not want to auto-approve since seeing the changes is part of the development process. 
However, we have to manually skip all the stacks with no changes before getting to the ones that may have changed on each loop.

Something like `--skip-no-changes` would speed up this use case significantly

Another useful flag would be to enable supression of "refresh" and "init" logs

**Comment by ansgarm** [comment]
Hi 👋

I just tested this and this issue is now obsolete since we refactored how we invoke the Terraform CLI.

In a short example with a chain of three stacks with each depending on the previous one, it didn't wait for approval on the first stack and last stack when there were only changes on the second one.

<img width="770" alt="Screenshot 2023-07-27 at 15 08 54" src="https://github.com/hashicorp/terraform-cdk/assets/1112056/b07fb1c0-1e47-4089-b365-e4958196c075">
