### ISSUE TITLE
Snowflake cdktf provider is out-of-date

### ISSUE THREAD

**Issue by manojkarthick** [hashicorp/terraform-cdk#2267]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The pre-built cdktf snowflake provider is out-of-date compared to the terraform provider. The pre-built provider seems to be pinned at `~>0.40`. Is there a way to upgrade it to track the new releases (currently [0.51.0](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest) as of 2 days ago).

### cdktf & Language Versions

cdktf version: 0.13.0
pre-built snowflake provider version: 3.0.12
Typescript version: 4.8.4 

### References

* Pre-built CDKtf provider for snowflake: https://github.com/cdktf/cdktf-provider-snowflake
* Snowflake terraform provider: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest
* npm package: https://www.npmjs.com/package/@cdktf/provider-snowflake

**Comment by ansgarm** [comment]
Hi @manojkarthick,

thanks for reporting! The version constraint `~>0.40` might look a bit confusing but it [allows](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#-3) upgrading to e.g. `0.51` – e.g. the [currently released version](https://github.com/cdktf/cdktf-provider-snowflake/blob/dcfa163bd9ceb6910717c74c58327e61ea5f9306/src/version.json#L2) is `0.47`.
That said, we check for provider updates daily but the last ones [failed](https://github.com/cdktf/cdktf-provider-snowflake/actions/runs/3425100531/jobs/5720385557), so that's something we need to look into.

**Comment by manojkarthick** [comment]
Thanks for explaining @ansgarm! The latest version has features I was looking for. Let me know if there's anything I can contribute to help get the updater working again.
