### ISSUE TITLE
Terraform Commands fail when no provider version is specified

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

all

### Affected Resource(s)

Provider requirements

### Debug Output

```
$(yarn bin)/cdktf diff
⠸ initializing typescript-vault...

Error: Invalid provider version constraint

Invalid version constraint "undefined" for provider vault.

Error: Invalid version constraint

  on cdk.tf.json line 10, in terraform.required_providers:
  10:       "vault": "undefined"

This string does not use correct version constraint syntax.

non-zero exit code 1
```

### Expected Behavior

When specifying a `cdktf.json` file like this:

```json
{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "vault"
  ]
}
```

I'd expect it to work properly for all cli comands.

### Actual Behavior

`diff` / `deploy` / `destroy` are broken

### Steps to Reproduce

- Specify `cdktf.json` file as described above
- run `cdktf get`
- run `cdktf diff`

**Comment by PacoVK** [comment]
Hey, i ran into the same issue, after digging deeper into that turned out, that i did the following:
* Create a project from template (i used java, however pretty sure this applys to all other languages)
* Templates don't have default providers, hence we define one according the documentation (and as you did) but WITHOUT version constraint
* execute `cdktf get` to load all providers and so forth --> succeeds
* now build project and all cdktf commands that require to run `terraform init` fail because of `Error: Invalid provider version constraint`
* Add version constraint to you provider and  execute `cdktf get` to update
* Failure is still there --> maybe this can be handled better!?

Now how i fixed it (again Java, however for other languages the provider location may be different but solution will basically be the same):
* For Java cdktf adds classes to you classpath as well as the provider under `resources` changes to cdktf.json seems not to apply once those resources are in place
* Delete the `resources` and therefore the former provider without the version constraint set and re-run  `cdktf get`
* After reloading provider correctly the issue is gone and cdktf works as expected

**Comment by PacoVK** [comment]
possible solution: add an option for `cdktf get` command to reload/ upgrade provider. See the behavour of Terraform for `terraform init -upgrade`

**Comment by danieldreier** [comment]
It's unclear to me whether users (please chime in!) actively oppose dependency pinning, but my impulse here is to see this as a UX problem resulting from us requiring users to manually edit `cdktf.json` to specify providers.

Based on my experience in Terraform Core, using providers that aren't pinned to at least a general range basically inevitably (eventually) results in an unplanned pain when a backwards-incompatible provider release happens.

I'm inclined to fix this with a UX more like what I proposed in https://github.com/hashicorp/terraform-cdk/issues/877 and avoid users needing to edit `cdktf.json` under normal circumstances. Alternatively, we could rely on the [Terraform dependency lock file](https://www.terraform.io/docs/language/dependency-lock.html) but I think we're signing people up for a problem down the road if we equate a missing  version string to latest.

**Comment by PacoVK** [comment]
@danieldreier in fact your proposal in #877 will help a lot and i agree to your points. Basically this is what i also suggested but as an extension to the existing `cdk get`. However having an install command and getting rid of manually editing `cdktf.json`is a more elegant way IMHO.
