### ISSUE TITLE
CDKTF CLI augmented logs match wrong resource

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2331]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* 0.14.1

### Affected Resource(s)

any

### Expected Behavior

Works correctly if the names don't intersect.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/1112056/203332500-c79cc0f7-666b-4c51-b5d4-5dea2f0e3b64.png">

### Actual Behavior

Augments the wrong resource name (wrong construct id in parentheses):

<img width="634" alt="image" src="https://user-images.githubusercontent.com/1112056/203332472-71e68430-44c5-4011-8ab7-2a681bbce746.png">

### Steps to Reproduce

```
new resource.Resource(this, "null_resource");
new resource.Resource(this, "null_resource2");
```

### References

- #0000

**Comment by mutahhir** [comment]
Here it's annoying, but even more annoying is when we do this in error outputs. And even more so when we throw an error on attribute values. That makes it look like we interpolated the wrong value and that's why Terraform is complaining.

![image](https://user-images.githubusercontent.com/573531/205909344-5ee20e9a-f5a3-4be2-bc65-c8519654cc83.png)
