### ISSUE TITLE
Create additional communication channels

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a gitter room and/or a slack channel or similar to get more conversation going. I see a couple main use cases so maybe more than one solution makes sense:

- Help grow a community. I've seen some active gitter rooms which really give a sense of community for open source projects.
- Provide a way for contributors to talk with the core team about ideas and implementation details. Slack might work better for this.

**Comment by stefanfreitag** [comment]
Offering communication channels is really a good idea! In the last days I already approached @skorfmann via Twitter to ask one or two questions, but this seems not the way forward. 
Gitter or Slack are both good candidates - Gitter would help me a bit more as I use it also for the AWS CDK (awslabs/aws-cdk).

Maybe it make also sense to encourage creating questions on StackOverflow using a certain tag like `cdktf`.

**Comment by anubhavmishra** [comment]
Thanks for creating this issue! All HashiCorp OSS projects use [HashiCorp Discuss](https://discuss.hashicorp.com) for their official channel for communication. CDK for Terraform has a category on discuss too: https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47

Please feel free to ask questions and offer solutions to other community members on HashiCorp Discuss. We like it because it is searchable and we can keep track of questions and feedback in a consistent way as we do with all HashiCorp projects.

**Comment by danieldreier** [comment]
I'm going to close this issue because HashiCorp Discuss is the official community communication channel. I completely understand the desire to have multiple channels, but I think the community benefit from centralizing those discussions in one place outweighs the benefit of each specific alternative - I've seen this work really well with the Terraform Core Discuss.
