### ISSUE TITLE
Compatibility with aws-cdk

### ISSUE THREAD

**Issue by andreialecu** [hashicorp/terraform-cdk#244]
I have been looking into cdktf and from what I understand it should allow configuring other resources besides AWS ones. We're using `aws-cdk` currently, but it would be nice to be able to integrate MongoDB Atlas management, as an example, into our stack as well.

What I don't understand exactly is if it's supposed to be compatible with aws-cdk. Can I just move my current `aws-cdk` based stack to `cdktf`?

If not, would this be something on the road map? I'm trying to understand why two competing solutions would exist. It seems that `aws-cdk` users would eventually want to migrate to `cdktf`, given the broader scope of supported services. It would be nice if `aws-cdk` constructs were a compatible subset of `cdktf`.

**Comment by skorfmann** [comment]
> I have been looking into cdktf and from what I understand it should allow configuring other resources besides AWS ones. We're using `aws-cdk` currently, but it would be nice to be able to integrate MongoDB Atlas management, as an example, into our stack as well.

At the moment, these would be two separate stacks, one with AWS CDK and one with `cdktf` for Atlas.  

What you could do in theory, is synthesizing the AWS CDK stack as a cloudformation resource in `cdktf` somehow. However, I think you'd loose lots of benefits which the AWS CDK has to offer around deployment handling (e.g. assets, pipelines, diffs, security features, ...). 

I think the other way around would also theoretically possible, probably with a custom resource to deploy synthesized terraform. 

But again, I wouldn't recommend any of these ways at the moment and keep it two separate apps.

> What I don't understand exactly is if it's supposed to be compatible with aws-cdk. Can I just move my current `aws-cdk` based stack to `cdktf`?

No, while it's sharing [Constructs](https://cdk.tf/constructs) and [jsii](https://cdk.tf/jsii) as the foundation, it's two different products.

> It would be nice if `aws-cdk` constructs were a compatible subset of `cdktf`.

Interoperability is certainly something which is on our radar and I'd hope that it's not too far away. It would be really nice to open up the aws-cdk constructs for `cdktf`, since I think there's been put a lot of effort into designing the L2 / L3 constructs for AWS and it would bring a lot of value to `cdktf` users. 

I'll update this issue when there's news around this topic.

**Comment by ansgarm** [comment]
Note for everyone stumbling on this issue: Alongside CDKTF 0.7 we released a first technical preview of the `AwsTerraformAdapter` ([docs](https://www.terraform.io/docs/cdktf/create-and-deploy/aws-adapter.html), [repo](https://github.com/hashicorp/cdktf-aws-cdk)) which enables you to use AWS CDK constructs with the CDK for Terraform. It is currently TypeScript only ([issue](https://github.com/hashicorp/terraform-cdk/issues/1193)) and comes with [limitations](https://www.terraform.io/docs/cdktf/create-and-deploy/aws-adapter.html#known-limitations). Have a look at the [examples](https://github.com/hashicorp/cdktf-aws-cdk/tree/main/examples) or [docs](https://www.terraform.io/docs/cdktf/create-and-deploy/aws-adapter.html) if you're interested 👀

**Comment by ansgarm** [comment]
I'm going to close this issue as the [`AwsTerraformAdapter`](https://www.terraform.io/docs/cdktf/create-and-deploy/aws-adapter.html) introduced initial compatibility with AWS CDK constructs. We have individual issues tagged with [`feature/aws-adapter`](https://github.com/hashicorp/terraform-cdk/labels/feature%2Faws-adapter) to track what is required for full support of AWS CDK constructs. If anything is missing or blocking you from using the adapter, feel free to create a new issue or vote / comment on the existing ones. We are also open for PRs in case you want to help 👍
