### ISSUE TITLE
Provider assume role

### ISSUE THREAD

**Issue by sherryxcheng** [hashicorp/terraform-cdk#253]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
0.0.12

### Affected Resource(s)
Provider

### Debug Output
$ terraform plan
 Error: Extraneous JSON object property
   on cdk.tf.json line 27, in provider.aws[0].assume_role:
   27:           "roleArn": "arn:aws:iam::******:role/******",
 No argument or block type is named "roleArn". Did you mean "role_arn"?
 Error: Extraneous JSON object property
   on cdk.tf.json line 28, in provider.aws[0].assume_role:
   28:           "sessionName": "******"
 No argument or block type is named "sessionName". Did you mean "session_name"?

### Expected Behavior
AwsProviderAssumeRole  should translate input role_arn and session_name as is. 

### Actual Behavior

role_arn  and session_name are compiled to roleArn and sessionName, which are not recognized by terraform.
### Steps to Reproduce
provider.add_override('assume_role',
                    AwsProviderAssumeRole(
                        role_arn='*****',
                        session_name='******'
                ))
commented out actually role info here.

**Comment by skorfmann** [comment]
Thanks for opening the issue. I just tried it, and this should work in Python:

```python
        AwsProvider(self, 'Aws',
            region='eu-central-1',
            assume_role=[AwsProviderAssumeRole(
                role_arn = "foo",
                session_name = "bar",
                external_id = "baz"
                )])
```
`assume_role` takes a list of `AwsProviderAssumeRole` instances, which is due to the way the Terraform provider schema describes this type. Here's an excerpt from the generated Python code:

```python
class AwsProviderConfig():
    def __init__(self, *, region: str, ..., assume_role: typing.Optional[typing.List["AwsProviderAssumeRole"]]=None, ...
```
I think there's potential to improve this, since `assume_role` will always take only one item. There are many similar occasions across all providers. I'll create a follow up issue for this.

@sherryxcheng Can you confirm this woks for you as well?

**Comment by sherryxcheng** [comment]
@skorfmann Thank you for looking at the issue report. 

Have you tried `terraform init`? The python code was able to compile into Terraform code as JSON. However, with unrecognized attributes 'sessionName' and 'roleArn', which need to be 'session_name' and 'role_arn' according to https://registry.terraform.io/providers/hashicorp/aws/latest/docs. What you think?

**Comment by skorfmann** [comment]
> Have you tried `terraform init`? The python code was able to compile into Terraform code as JSON. However, with unrecognized attributes 'sessionName' and 'roleArn', which need to be 'session_name' and 'role_arn' according to https://registry.terraform.io/providers/hashicorp/aws/latest/docs. What you think?

```python
provider.add_override('assume_role',
  AwsProviderAssumeRole(
    role_arn='',
    session_name='*'
))
```

That's due to using `addOverride` here. That's an [escape hatch](https://cdk.tf/escape-hatch), which intentionally is passing down to the synthesized Terraform JSON whatever you provide there. When you use the `AwsProviderAssumeRole` class to provide the data here, it'll be camel-cased since that's the way it's stored internally.

When you look at the example I posted, it doesn't make use of the escape hatch, but uses the input options of the `AwsProvider` class. That way, the attributes will be correctly synthesized in snake-case.

```python
        AwsProvider(self, 'Aws',
            region='eu-central-1',
            assume_role=[AwsProviderAssumeRole(
                role_arn = "foo",
                session_name = "bar",
                external_id = "baz"
                )])
````

**Comment by sherryxcheng** [comment]
I see. Specify assume_role in the provider directly works for me. Thanks!
