### ISSUE TITLE
CDKTF plan running locally instead of remote with latest version (0.15.2)

### ISSUE THREAD

**Issue by sabinayakc** [hashicorp/terraform-cdk#2555]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
v0.15.2 

### Affected Resource(s)

`cdktf plan`

### Debug Output
```
language: typescript
cdktf-cli: 0.15.2
node: v16.17.0
cdktf: 0.15.2
constructs: 10.1.230
jsii: null
terraform: 1.3.7
arch: x64
os: linux 5.10.102.1-microsoft-standard-WSL2
```

### Expected Behavior

When using Terraform Cloud Backend with `Remote` plan settings, `cdktf plan <stack-name>` should run remotely.
![image](https://user-images.githubusercontent.com/13154166/215562509-b8465804-93f4-4b66-944a-f255b99e9f9c.png)

### Actual Behavior

When using Terraform Cloud Backend with `Remote` plan settings, `cdktf plan <stack-name>` is running locally.
It also creates `.terraform` folder under stacks which should not happen for cloud run. 

![image](https://user-images.githubusercontent.com/13154166/215562367-d6e5ff78-3e82-4175-b90d-73d5c6e9aef8.png)

### Steps to Reproduce

- Upgrade to latest cli and cdktf version (0.15.2)
- Create a cloud workspace and connect your stack using `CloudBackend`.
- In the workspace setting, enable "Remote" for execution setting
![image](https://user-images.githubusercontent.com/13154166/215561432-e5dfe69a-4296-46e6-8507-42060ef85cd0.png)
- Run `cdtkf plan <stack>`

### Important Factoids

- Downgrading to v0.14.3 works. 
- 

### References

- #2543 
- #2538

**Comment by mutahhir** [comment]
Hi there, I'm afraid it's a bit hard to action on this without more information. Can you provide:

- A bit more output from the `cdktf plan` above. 
- A part of the CloudBackend code that you can share. 

Since 0.15, we've moved to using the Terraform CLI, so the output might be different from what you expect. In the screenshot supplied above, it looks like the Terraform `init` command output. We do that to ensure that terraform can run the plan or apply properly afterwards, but it doesn't mean that your plan will be executed locally.

When you continue running the `plan` command from the screenshot, do you not get a TFC link to the remote run?

**Comment by sabinayakc** [comment]
@mutahhir  Yes, when I run plan it is giving me a remote link. 

However I just want to highlight the following, 
- CDKTF 0.14.3 did not download and create .terraform folder inside stack and a lock file, since we have selected a `Remote` run/plan, it actually did that in the cloud. (This is the current behavior in 0.14.3).
- In 0.14.3 i dont see any .terraform folder inside the stack, unless as you said that has changed? 
- CDKTF 0.15.2 plan is displaying the traditional console output in Remote, instead of doing the Structure Output even if we have specified the workspace to use the Structured UI Output.
- I am suspecting , `cdktf plan` and `cdktf apply`  is planning locally and using the cloud to just store the state file ?

If you think above are the expected behavior then I am fine with closing this out. But I just wanted to point out the different behavior in the latest version.

**Comment by mutahhir** [comment]
The biggest difference between 0.14.x and 0.15.x is that we're now using the Terraform CLI to execute plans, applies, and destroys. Before this, we were using TFC's [API-Driven Run Workflow](https://developer.hashicorp.com/terraform/cloud-docs/run/api), so the apparent behaviour will be different.

When Terraform CLI runs, [it generates a few files and folders as outlined here](https://developer.hashicorp.com/terraform/cli/init#working-directory-contents), but you should only see the `.terraform` folder which contains some caches, a [provider lock file](https://developer.hashicorp.com/terraform/language/files/dependency-lock#lock-file-location), and not any `terraform.tfstate` files that represent local state.

Also, you're seeing runs being performed on the TFC web interface as well, right? That only happens when TFC itself executes the plan / apply / destroy, I believe.

I'm going to assume that since the remote link is available, and the workspace is set to remote execution, CDKTF is doing the right thing. Please reopen this issue if I misunderstood, or if this assumption is incorrect. I'd be happy to follow up.

**Comment by sabinayakc** [comment]
@mutahhir , Thanks for the clarification.

However, couple of issues:
- The plan is a lot slower now. 
- cdktf plan runs `terraform init` and downloads providers on every cdtkf plan. 
- The plan in TFC still shows a consule UI output instead of the structured UI output.
