### ISSUE TITLE
provider-aws >11.0.8 breaks defaultTags

### ISSUE THREAD

**Issue by labmonkey42** [hashicorp/terraform-cdk#2565]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.14.3
nodejs 16.18.0

### Affected Resource(s)

AwsProvider
AwsProviderConfig

### Expected Behavior

Instantiate a provider as:
```Typescript
new AwsProvider(this, 'foo', { defaultTags: { tags: { 'foo': 'bar' } } });
```
works as stated in AWS provider documentation.

### Actual Behavior

Provider now expects `defaultTags` to be an _array_ of `AwsProviderDefaultTags`:
```Typescript
new AwsProvider(this, 'foo', { defaultTags: [ { tags: { 'foo': 'bar' } } ] });
```
to be valid.

### Steps to Reproduce

Upgrade '@cdktf/provider-aws' to >=11.0.9 and try to use `defaultTags` as documented.

### Important Factoids

I found this when trying to upgrade to 0.15.*.  In our case the stack has some of its own default tags and accepts a provider config parameter from which I merge default tags in order to override.  The combination of `AwsProviderDefaultTags[]` and `IResolvable` results in my linter insisting that I can't reference `defaultTags[0]` and I also can't just append or merge these two objects.

Offending change: https://github.com/cdktf/cdktf-provider-aws/compare/v11.0.8...v11.0.9 src/provider/index.ts introduced this array/IResolvable change.

(edit: corrected typo)

**Comment by ansgarm** [comment]
Hi @labmonkey42 👋

I found the underlying reason for this change to an array. The AWS provider version `4.53.0` specifies the type for `default_tags` as follows:
```
            "default_tags": {
              "nesting_mode": "list",
              "block": {
                "attributes": {
                  "tags": {
                    "type": [
                      "map",
                      "string"
                    ],
                    "description": "Resource tags to default across all resources",
                    "description_kind": "plain",
                    "optional": true
                  }
                },
                "description": "Configuration block with settings to default resource tags across all resources.",
                "description_kind": "plain"
              }
            },
```

Whereas previous versions, like e.g. `4.47.0` specified it as:
```
            "default_tags": {
              "nesting_mode": "list",
              "block": {
                "attributes": {
                  "tags": {
                    "type": [
                      "map",
                      "string"
                    ],
                    "description": "Resource tags to default across all resources",
                    "description_kind": "plain",
                    "optional": true
                  }
                },
                "description": "Configuration block with settings to default resource tags across all resources.",
                "description_kind": "plain"
              },
              "max_items": 1
            },
```

The difference here is `"max_items": 1` which in the past caused CDKTF to skip wrapping this in an array but now requires setting an array.

The underlying reason is that in HCL it is allowed to write e.g.
```hcl
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Environment = "Test"
    }
  }
  default_tags {
    tags = {
      Name = "Hello"
    }
  }
}
```

whereas in TypeScript (and other languages) it is not possible to have the same key twice on the same record.

Depending on how your code is structured, you might be able to use `provider.defaultTagsInput[0]` which accesses the exact value you passed to your provider. But if you're using tokens or other values that are only known at plan/apply time, you'd have to resort to a Terraform function and call e.g. `Fn.element(provider.defaultTags, 0)` to get the map that was passed to the provider.

**Comment by ewbankkit** [comment]
`MaxItems: 1` is still in that attribute's schema: https://github.com/hashicorp/terraform-provider-aws/blob/77816b9e552f9e13f24c166e73fbdeafd97b6d01/internal/provider/provider.go#L229-L244.

**Comment by xiehan** [comment]
We should test to see if this is resolved with v5.0 of the AWS provider.

**Comment by DanielMSchmidt** [comment]
The Aws provider in version 5.5.0 does not have the `max_items` attribute:

```json
{
  "nesting_mode": "list",
  "block": {
    "attributes": {
      "tags": {
        "type": [
          "map",
          "string"
        ],
        "description": "Resource tags to default across all resources",
        "description_kind": "plain",
        "optional": true
      }
    },
    "description": "Configuration block with settings to default resource tags across all resources.",
    "description_kind": "plain"
  }
}
```

I wonder why since the max_items attribute is still not there: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/provider/provider.go#L56-L71 Maybe this should be raised at the AWS provider?

**Comment by oshea00** [comment]
I can attest this was confusing for my C# implementation as the intellisense was of little help and the compiler didn't complain, it surfaced as a runtime problem.  Took about 2 hours of my life to come up with this. Maybe it will help the next person:
```
            new AwsProvider(this, "AWS", new AwsProviderConfig { 
                Region = "us-west-1",
                DefaultTags = new AwsProviderDefaultTags[] {
                    new AwsProviderDefaultTags {
                        Tags = new Dictionary<string, string> {
                            {"AppId",            "TBD01"},
                            {"AppName",          "Example CDKTF"},
                        }
                    }
                }
            });

```

**Comment by ansgarm** [comment]
Hi @labmonkey42, @oshea00 👋

The underlying reason for this being an array now, is that the attribute is defined as a block as opposed to being defined as an attribute which is handled differently in newer versions of the Terraform since the support for min and max items has been dropped (https://github.com/hashicorp/terraform/pull/29648, as posted by @ewbankkit).

The semantic difference between these two types is that blocks can be changed to allow multiple items without a breaking change, whereas attributes would need to change their type from object to array of object.

From our (CDKTF) point of view, the semantically correct definition for the `default_tags` argument should be an attribute instead of a block. However, I suspect that a block is used for historical reasons to not break existing Terraform configuration (changing from block to attribute requires changes to existing Terraform code, as attributes are assigned using `=` when writing HCL).

At this point, we'd treat this as a documentation issue. Thank you @oshea00 for posting a C# example for this!
For TypeScript and Python the translated docs in the Registry already include the array in the provider documentation for `default_tags`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs?lang=typescript#default_tags-configuration-block

I'm going to close this issue at this point, but if anyone runs into any other issues with this, please don't refrain from filing a new bug or feature request!
