### ISSUE TITLE
`node_modules` folder is packed and published to npm

### ISSUE THREAD

**Issue by NetaNir** [hashicorp/terraform-cdk#2819]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

TypeScript/Javascript
### Affected Resource(s)

The package published to npm includes the `node_modules` folder, as a result, in some environments (enterprise... 🫣), importing it is blocked. 

### Debug Output

n/a

### Expected Behavior

no `node_modules` in published artifact please :)
### Actual Behavior

https://registry.npmjs.org/cdktf/-/cdktf-0.16.0.tgz

### Steps to Reproduce

Download and unzip the above link, you will see the `node_module` folder
### Important Factoids

I think this can be solved by adding `node_module` to the `.npmignore` file, like the CDK did here for the `test` folder. If we agree this is the right solution, happy to raise a PR.

### References

- #0000

**Comment by ansgarm** [comment]
Hi @NetaNir 👋

Thanks for raising this! Upon deeper investigation this appears to happen because we have `bundledDependencies` specified for that package, which is required by JSII.

I had a quick look and it seems like the `aws-cdk-lib` package also includes `node_modules` – so it seems like there's no way around this when using JSII.

How do enterprises handle these cases for packages that make use of bundled dependencies? Maybe there's a way around those somehow?

**Comment by NetaNir** [comment]
oh, interesting, let me look at `aws-cdk-lib` and figure out whats up there.
