### ISSUE TITLE
Please keep support for Java Maven

### ISSUE THREAD

**Issue by karlbennettvector** [hashicorp/terraform-cdk#3105]
### Description

The latest release of the terraform-cdk (0.18.0) has changed the Java build tool from [Maven](https://maven.apache.org/) to [Gradle](https://gradle.org/).

```shell
$ cdktf init --template="java" --providers="akamai/akamai" --local
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.<STACK NAME>.tfstate' in the root of your project.
? Project Name test
? Project Description A simple getting started project for cdktf.
? Do you want to send crash reports to the CDKTF team? Refer to https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/configuration-file#enable-crash-reporting-for-the-cli for more information no
Unable to find "gradle". Install from https://maven.apache.org/install.html
```

Maven is a much more mature, stable, supported, and maintainable build tool. Could we please revert the terraform-cdk back to using Maven or give the user the option to choose if they wish to use Maven or Gradle?

### References

- https://github.com/hashicorp/terraform-cdk/commit/a196f347a16145b920ae2a16e5b8c3220662bb8d

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
Hey there,
We moved over to Gradle to [improve the synth / build time performance](https://www.hashicorp.com/blog/cdk-for-terraform-0-18-reduces-synthesization-time) and we are measuring great results. This is why we want to use Gradle in the future as well to have a performant default for init so that new users have a great experience. 
If you still want to use Maven you are free to, all our tools like `cdktf provider add` still support maven and the cdktf library also still works with Maven. If you want to provide the community with the option to start out with Maven, we do support remote templates with `cdktf init` where you can put any github repository in and use [sscaff scaffolding](https://github.com/cdklabs/node-sscaff). Or you can use a template repository, whatever is more convenient to you :)
