### ISSUE TITLE
cdktf diff on main.ts is not deploying multiple Terraform Stacks

### ISSUE THREAD

**Issue by TirushV** [hashicorp/terraform-cdk#3500]
### Expected Behavior

Deploy/Diff multiple stacks with root stack when calling from main.ts

Stack1 -> TerraformStack (in a file)
Stack2 -> TerraformStack (in another file)
Calling these 2 stacks in main.ts is not deploying anything

Says no changes to infrastructure.

### Actual Behavior

Deploy/Diff multiple stacks with root stack when calling from main.ts

Stack1 -> TerraformStack (in a file)
Stack2 -> TerraformStack (in another file)
Calling these 2 stacks in main.ts is not deploying anything

Says no changes to infrastructure. -> Should be able to list and deploy multiple stacks without explicitly defining `cdktf diff` command

### Steps to Reproduce

1. Able to get difference of all the stacks from `cdktf diff` command instead of explicitly defining stacks.
2. Able to deploy stacks without approval.
3. Able to deploy single or multiple stacks from this command `cdktf deploy`

### Versions

language: Typescript
cdktf - 0.20.3
terraform - Terraform v1.7.2
on darwin_arm64

### Providers

Datadog

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
> Able to get difference of all the stacks from cdktf diff command instead of explicitly defining stacks.

That is not possible and likely will never be. [See #2235](https://github.com/hashicorp/terraform-cdk/issues/2235#issuecomment-1303289768) for more detail, TL;DR is due to cross stack references we can not guarantee the correctness of a plan.

> Able to deploy stacks without approval.

You can, e.g. if you want to do all stacks do `cdktf deploy --auto-approve '*'`

> Able to deploy single or multiple stacks from this command cdktf deploy

You can, see [the examples](https://developer.hashicorp.com/terraform/cdktf/cli-reference/commands#deploy) in the docs.

I'm closing this in favour for #2235, if I misunderstood sth please don't hesitate to re-open

**Comment by TirushV** [comment]
Thank you
