### ISSUE TITLE
Best practices for organizing projects

### ISSUE THREAD

**Issue by netzere** [hashicorp/terraform-cdk#399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, i think we should add some documentation regarding some best practices.
For example like in: https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/

For example, one common use case is to deploy a stack across multiple environments with slightly different parameters. 
With terraform, we would probably create a module, and then reuse it in our environment implementations ("dev", "stage", "prod").
How this should be done when using cdktf?

**Comment by skorfmann** [comment]
Complex, multi stack scenarios are a bit difficult to build at the moment since we support only one stack right now. However, with #289 that'll change and will enable these complex scenarios more easily. 

If you'd want to deploy the same stack in different configurations, you could also use [Terraform Workspaces](https://www.terraform.io/docs/state/workspaces.html)

**Comment by Mikkel-Gram** [comment]
How is the workspaces supposed to work with cdktf? I would expect to be able to call something like:
`cdktf workspace init NewWorkspace` followed by 
`cdktf deploy`
But i can really find this functionality in the CLI.
Do I have to go to the terraform CLI in order to select/create workspaces and thus not be fully able to use cdktf for everything? 
I have also seen some examples of defining the workspaces in the IaC-code, but that seems to somewhat defeat the purpose i think?
Maybe i am overlooking something somewhere about how to use the CLI to manage workspaces, but if not this is really needed imo :)

**Comment by jsteinich** [comment]
Using workspaces directly from cdktf isn't currently supported.
There are currently some issues interacting with Terraform workspaces as well. See #376 for some more info.

**Comment by jsteinich** [comment]
I would say supporting multiple environments is definitely planned functionality. I'm not certain if that will involve terraform workspaces, but it does seem like a good candidate.

You should be able to use cdktf for everything besides the workspace management (creating, switching). It sounds like there may be some issues with a local state file (even if using remote state). So may need to do some manual management of that for the time being.

**Comment by skorfmann** [comment]
@Mikkel-Gram since `workspace` is a bit overloaded in meaning: Are you talking about using workspaces to model something like `dev`, `staging` and `production` environments for the the same Terraform configuration?

**Comment by Mikkel-Gram** [comment]
Yea i was referring to Terraform workspaces although i realize now it could be implemented in a different way for the cdk 😊
But yea basically i just want to be able to deploy identical environments like dev, staging,prod, from the exact same cdktf code 😊

**Comment by skorfmann** [comment]
Ok, thanks for clarifying. Essentially what @jsteinich said, we don't support workspace management via the `cdktf-cli` at the moment. You could fallback to the Terraform CLI though.

**Comment by Mikkel-Gram** [comment]
cool, thanks for the info :) 
do you know if this is on the roadmap (is there some place i can see about what is planned?) as im guessing this is an important feature for a lot of users

**Comment by skorfmann** [comment]
> do you know if this is on the roadmap (is there some place i can see about what is planned?) as im guessing this is an important feature for a lot of users

Here's something like a roadmap, it's more like a rough guideline at this point https://github.com/orgs/hashicorp/projects/77

**Comment by DanielMSchmidt** [comment]
We now have https://www.terraform.io/cdktf/create-and-deploy/best-practices, so it's done
