### ISSUE TITLE
Computed Lists and Maps

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#42]
With the current implementation of computed Lists and Maps we can access single elements (see #31 / #12). What we can't do right now:

- Iterate programatically
- Pass a computed List / Map as input to another Resource / Module

**Comment by DanielMSchmidt** [comment]
- #993 Tracks our move from ComplexComputedLists to Arrays
- #1089 Tracks iterating on lists 
- #1130 is a PR for for expressions
- We implemented Maps already, since everything in this issue seems to be tracked somewhere else I am going to close this one for now. If I am too eager here, please let me know 👍
