### ISSUE TITLE
Make Homebrew formula require either `terraform` or `tfenv`

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-cdk#475]
You can't rely on the fact that everybody is using the latest version of Terraform. Given how buggy `v0.14` has been, some of us have switched to `tfenv`.

**Comment by skorfmann** [comment]
thanks for opening this issue @nikolay. Do you happen to know how this could be expressed in the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cdktf.rb)?

**Comment by cmclaughlin** [comment]
I would like to see this happen too... so I opened this PR a few months ago, but it was closed out as "won't fix":

https://github.com/Homebrew/homebrew-core/pull/61952

I don't think homebrew supports optional or recommended dependencies, so the either/or part seems to be impossible.

**Comment by skorfmann** [comment]
> I would like to see this happen too... so I opened this PR a few months ago, but it was closed out as "won't fix":
> 
> [Homebrew/homebrew-core#61952](https://github.com/Homebrew/homebrew-core/pull/61952)

Oh, interesting! Thanks for linking it here. 

Trying to understand your use-cases a bit better: What's your primary reason to use Homebrew in the first place (compared to doing a plain `npm install`)?

**Comment by cmclaughlin** [comment]
I don't venture into nodejs development very often, so installing cdktf via homebrew is appealing just for the sake of ease of use and simplicity.  It's one less thing to remember how it works and what to do when it doesn't work.

Regarding tfenv versue terraform, we have a stacks using a variety of Terraform versions and since the state is version specific, tfenv solves that problem.

**Comment by skorfmann** [comment]
> I don't venture into nodejs development very often, so installing cdktf via homebrew is appealing just for the sake of ease of use and simplicity. It's one less thing to remember how it works and what to do when it doesn't work.

Ok, that makes sense. Thanks for elaborating.

> Regarding tfenv versus terraform, we have a stacks using a variety of Terraform versions and since the state is version specific, tfenv solves that problem.

One comment in your [PR](https://github.com/Homebrew/homebrew-core/pull/61952) mentions [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) as a potential workaround. Would this be helpful? Or perhaps there could be a dedicated formula, like `cdktf-tfenv`?

**Comment by cmclaughlin** [comment]
Yeah that might help. But as I said in the PR, I lost the momentum, gave up and moved on.

**Comment by skorfmann** [comment]
Ok, so sum it up:

There doesn't seem to be a way to have either/or dependencies in Homebrew. I think it makes sense that the `cdktf` homebrew package has a dependency on Terraform. If there's demand for a `cdktf-tfenv` package, the right place to propose this would be the [Homebrew repository](https://github.com/Homebrew/homebrew-core). 

One could fork & adapt the existing [cdktf formula](https://github.com/Homebrew/homebrew-core/blob/745fcd5a474c253e5bc05813b4d777de43cb0ed3/Formula/cdktf.rb) with minimal effort, but I don't know the odds of getting it merged. The alternative would be maintaining a [Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). If anyone wants to take this, I'm happy to extend our [release workflow](https://github.com/hashicorp/terraform-cdk/blob/790ab578c307b5efef62777be4ab11d62ec45b6a/.github/workflows/release.yml#L117-L138) to automatically bump the version.

Gonna close this issue here.
