### ISSUE TITLE
dependency is incorrectly generated for the terraform-module

### ISSUE THREAD

**Issue by andrey-dubnik** [hashicorp/terraform-cdk#507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdkf 0.1.0
Java

### Affected Resource(s)

terraform-module

### Expected Behavior

depends_on not dependsOn in the synth JSON

### Steps to Reproduce

Create any module with depends on

```
TerraformHclModule.Builder.create(this, "module")
            .dependsOn(List.of(rg))
```

### References

https://github.com/hashicorp/terraform-cdk/blob/16153024623c5367454bb6b4810ff38fedf12b4f/packages/cdktf/lib/terraform-module.ts#L75

Should probably go via similar  keysToSnakeCase transformation to 

https://github.com/hashicorp/terraform-cdk/blob/16153024623c5367454bb6b4810ff38fedf12b4f/packages/cdktf/lib/terraform-resource.ts#L108

**Comment by skorfmann** [comment]
@andrey-dubnik Thanks for raising this issue. Yes, this should be snake-cased. I'm wondering if just changing the `dependsOn` [key](https://github.com/hashicorp/terraform-cdk/blob/16153024623c5367454bb6b4810ff38fedf12b4f/packages/cdktf/lib/terraform-module.ts#L75) would be sufficient.

Out of curiosity, what's your reason to use TerraformModule rather than [imports](https://github.com/hashicorp/terraform-cdk/blob/16153024623c5367454bb6b4810ff38fedf12b4f/docs/working-with-cdk-for-terraform/using-providers-and-modules.md#importing-providers-and-modules)?

**Comment by andrey-dubnik** [comment]
Changing the property may do it as well, although this would probably cause the lack of clarity which approach to take by addressing the same problem differently within the code base.

It seem imports can only handle modules from the public hashicorp registry where we use a private one hence needed to use a different approach with the TerraformModule.

**Comment by skorfmann** [comment]
> It seem imports can only handle modules from the public hashicorp registry where we use a private one hence needed to use a different approach with the TerraformModule.

Yes, true. That's a current limitation which we'll be addressing in the future. Thanks for your feedback.

> Changing the property may do it as well, although this would probably cause the lack of clarity which approach to take by addressing the same problem differently within the code base.

Absolutely. `keysToSnakeCase` turned out to be too greedy in some cases in the past. I'm not sure if `terraformMetadata` could potentially include user supplied objects which would cause the same issues again. So, that's something to double check where `keysToSnakeCase` is used. In this particular case, it's deviating from the other implementations already, due to the custom handling around providers.
