### ISSUE TITLE
Publish C# aws project as nuget package, not source files on disk

### ISSUE THREAD

**Issue by mikeparker** [hashicorp/terraform-cdk#534]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be more standard and efficient and user friendly to ship the aws project as a nuget package rather than having the generated C# on disk.

Firstly, I am attempting to initialise a git repository containing some minimal C# cdktf files and Visual Studio Code is showing 5k+ local files under the .gen/aws/ folder. Since there is no .gen in the .gitignore file its unclear whether I should be syncing this entire directory under my own source control, which feels ugly and inefficient (why should we be compiling this code manually locally?), but then again the generated C# code has a project reference directly to the aws project on disk, so either every user must either upload and host all 5k+ files or gitignore the directory and have a broken build whenever someone else tries to compile the project. This should be replaced with a nuget package.

Secondly, `cdktf get` is surprisingly slow (like 30sec). I'm guessing this is either generating all this C# from scratch or its untarring the files? If I was going to set up a CICD pipeline to do this, this step would be frustratingly slow (and cost money). As a developer tools and automation company I'm sure you are aware how these inefficiencies add up to a bad user experience and I'm sure this could be solved using nuget.

As a secondary issue it's unclear how exactly I should be using this tool in CICD. I am happy to set up a basic github action pipeline to generate the terraform and open a PR to a terraform repo with the changes, but its unclear exactly what the expectation is on the cicd pipeline around generating the providers (or having them already present). My _guess_ would be to gitignore the .gen folder and then generate the files every time I run CICD but as above thats a bit inefficient and could break if regenerating the providers changes in some way.

**Comment by jsteinich** [comment]
I believe the plan is to publish a set of core providers to NuGet.org. Now that the core cdktf package is published, I would expect that to be coming before long.

I believe there will always be some providers or modules that won't be published, so the choice is up to the user to decide how to handle the generated files. Some options I can think of:

- Commit them as is. This has the benefit of complete visibility to changes a the cost of storing and compiling those files.
- Ignore them. No longer need to store, but developer experience is hurt since an init step is required.
- Publish internally. Easy for consumers and quicker builds, but some overhead in setting up / maintaining publish step.

The slowness is something we are aware of and there are some open issues in upstream libraries to help with that.

**Comment by mikeparker** [comment]
Great to hear it, that all sounds good!

**Comment by skorfmann** [comment]
> I believe the plan is to publish a set of core providers to NuGet.org. Now that the core cdktf package is published, I would expect that to be coming before long.

yes, that's coming this week 👍

**Comment by skorfmann** [comment]
So, that took a while. Now, all pre-built provider packages (including [AWS](https://www.nuget.org/packages/HashiCorp.Cdktf.Providers.Aws/)) are now [published to nuget](https://www.nuget.org/profiles/hashicorp) as well. See https://github.com/terraform-cdk-providers/cdktf-provider-project/pull/111
