### ISSUE TITLE
Deploy cross account using Gitlab runners

### ISSUE THREAD

**Issue by jvargh** [hashicorp/terraform-cdk#540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Is there working sample or documentation to show how CDK-TF with aws provider could deploy cross account with gitlab pipeline? main emphasis here is to maintain unique TF state per environment/aws account

**Comment by skorfmann** [comment]
> Is there working sample or documentation to show how CDK-TF with aws provider could deploy cross account with gitlab pipeline? main emphasis here is to maintain unique TF state per environment/aws account

I don't think there's a specific example for this. It will also depend on your desired workflow. Could you provide a few more details how this would look like in your case? How are you doing this at the moment?

What we don't support at the moment, to synth / deploy multiple stacks in one go (see #35). Having said that, it's still something you could likely achieve by orchestrating it manually.

**Comment by jvargh** [comment]
Its a greenfield setup using cdktf. Workflow would involve deploying to different stages (qa, prod), each stage with variances (varying db types, cpu, mem) and the TF state should be stored for its respective state

**Comment by jsteinich** [comment]
I'm currently using [Terraform Atlantis](https://www.runatlantis.io/).
I have different Terraform workspaces for each environment.
Currently using local synth and Terraform variables for the varying parameters since that's how we were doing it pre-cdktf; however, I don't recommend that approach if you have conditional resources.
I plan to switch to language specific configuration files and let Atlantis handle the synth step so that I can better use if statements and such. That would also be helpful if you plan to store the state in different locations per environment.

**Comment by skorfmann** [comment]
Since this issue looks stale on not really actionable, I'm gonna close this. Please let us know if there's still the need for more input.
