### ISSUE TITLE
Integration with GitOps continuous delivery tool

### ISSUE THREAD

**Issue by jvargh** [hashicorp/terraform-cdk#546]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Is there any guidance/samples on using CDK-TF with CD tool as Argo CD?

**Comment by jvargh** [comment]
@skorfmann @jsteinich any suggestions would be greatly appreciated

**Comment by jsteinich** [comment]
The general steps are:

1. Checkout code
2. Run `cdktf get` (this step can be omitted if only using pre-built providers or generated sources are committed)
3. Run `cdktf diff` (useful to be able to preview changes before making them)
4. Manually approve changes (may be possible to omit this, but I certainly feel more comfortable approving changes)
5. Run `cdktf deploy`

I'm currently using [Terraform Atlantis](https://www.runatlantis.io/) and local synth since it was easiest to map into existing Terraform workflows, but am planning to using a custom workflow to execute the synth from Atlantis.

**Comment by skorfmann** [comment]
> but am planning to using a custom workflow to execute the synth from Atlantis.

That would make a great demo :)

**Comment by skorfmann** [comment]
Closing since it seems to be stale
