### ISSUE TITLE
Import from Terraform doesn't pass config to TerraformHclModule correctly

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#860]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Latest build from main

### Affected Resource(s)

Modules not from registry

### Expected Behavior

configuration passed to modules passed in variables map

### Actual Behavior

Configuration values are passed to directly in configuration object

### Steps to Reproduce

1. Create Terraform file that references a non-registry module that requires passing configuration
2. Run cdktf init from terraform
3. Run cdktf synth

**Comment by DanielMSchmidt** [comment]
I spiked into converting modules as well just to get a feeling for how hard it would be. It's quite some effort I am afraid since they can be used recursively and we would need to get the type information about the interface. It's not undoable, but there is quite some handling that is different from the normal conversion (inputs, outputs, etc.). My POC branch is `feat-recursive-module-conversion`. We should fix this differently, by changing the current generation to fit the API of TerraformHclModule

**Comment by jsteinich** [comment]
I'll take a look at your branch when I get a chance.
We do already support code generation for modules so we may want to solve some of those issues regardless.
