### ISSUE TITLE
Remote backend execution mode "local" in terraform code

### ISSUE THREAD

**Issue by DidelotK** [hashicorp/terraform-cdk#923]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When i use remote backend, i would like to be able to set execution mode directly on the tf files like this :
```
  backend "remote" {
    organization = "TOTO"

    workspaces {
      prefix = "infra-"
      execution_mode = "local" <----- Would be perfect
    }
  }
```

For the moment i have to go on the platform and manually for each env set local.

**Comment by danieldreier** [comment]
Hi @DidelotK - thanks for filing this feature request. It looks to me like this is a request for [Terraform Core](https://github.com/hashicorp/terraform) rather than the CDK for Terraform project, so I'm going to close this for now. If this is implemented in Terraform Core we'll be able to support it on the CDK side as well.
