### ISSUE TITLE
[Typescript] Make static reference to generated Constructs

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#93]
We can add the following to the `tsconfig.json` file:

```json
    "baseUrl": "./",
    "paths": {
      "providers/*": [".gen/providers/*"]
    }
```

This will allow 

```typescript
// instead of 
import { AwsProvider, Alb } from './.gen/providers/aws';

// we can do this
import { AwsProvider, Alb } from 'providers/aws';
```
Since that's a static reference, we can easily move files around without having to update the import statements.

**Comment by zukwung** [comment]
@skorfmann and anyone who ends up here from google, I actually was looking into this issue and found that since cdktf runs `npx ts-node main.ts`, you can actually configure your `tsconfig.json` following the [docs here](https://www.npmjs.com/package/ts-node#paths-and-baseurl) to resolve any path aliases you've defined, even if its not the `.gen` folder. 

Hope this helps, but it would be nice to document this somewhere (though I don't know where) to save 2 hours for someone else who sucks at typescript.
