### ISSUE TITLE
[Docs page] CDKTF Best Practices

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#974]
**Description**

:tickets: [Asana ticket](https://app.asana.com/0/1200893566367079/1200893566367091)

:mag: File path: /website/docs/cdktf/concepts/best-practices.html.md

Broad recommendations for folks as they’re setting up their projects

**Comment by schersh** [comment]
@laurapacilio related issue: https://github.com/hashicorp/terraform-cdk/issues/399

**Comment by ansgarm** [comment]
Some (incomplete) ideas for what could be mentioned on a best practices page:
* How to pass variables / secrets to e.g. `cdktf deploy`
* How to iterate over data available at synth time and over data available at run time (when TF runs)
* Why pre-built providers should be preferred (e.g. faster builds, enables shared custom constructs)
* Should one use `terraform.workspace`? Why not / what to use instead (stacks probably, we'd have to check)
* Using custom constructs instead of Terraform modules for building blocks

**Comment by laurapacilio** [comment]
good ideas, ansgar! I also even just wondering if we could modify existing docs pages to cover these topics. Then users would see it in context - for example, maybe the variables pages needs to talk about secrets, etc.  I can think more about this - but I also have an internal ideas doc that Sarah can share with some tentative "best practices" deliverables for Q2 :-)

**Comment by ansgarm** [comment]
> modify existing docs pages to cover these topics

Yeah, sure! That would also work 👍

**Comment by schersh** [comment]
Related? https://github.com/hashicorp/terraform-cdk/issues/399
